name: ❓ Other
description: Create some other type of issue
title: '<title>'
labels: ['🚦 needs triage']
body:
  - type: checkboxes
    attributes:
      label: Is an Issue Type Set?
      description: 'Choose a type for this issue: ♻️ refactor, ✅ test, 🌍 i18n, 🎨 style, 👷 ci, 📝 docs, 🔒 security, 🔧 build, 🗄️ epic, 🚀 performance.'
      options:
        - label: I've added a label to the issue (if possible)
          required: false
  - type: textarea
    attributes:
      label: What?
      description: Describe what you want to do.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why?
      description: What problem would this solve?
    validations:
      required: true
