name: Sync labels
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v6
      - uses: brpaz/action-label-syncer@master
        with:
          prune: false
          manifest: .github/labels.yml
          repository: |
            twocaretcat/.github
            twocaretcat/168421
            twocaretcat/calculator
            twocaretcat/dotfiles
            twocaretcat/Image-Signer
            twocaretcat/twocaretcat
            twocaretcat/twocaretcat.github.io
            twocaretcat/NoBS
            twocaretcat/rtg-for-outlook
          token: ${{ secrets.GH_TOKEN }}
